# fly.toml app configuration file generated for test-sqslite on 2024-08-31T20:31:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-sqslite'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
[processes]
   app = "bun src/index.ts fly:server"
   worker = "bun src/worker.ts"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
